server:
  port: 1111

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: action_rest_service_route
              uri: lb://ACTION-REST-SERVICE
              predicates:
                - Path=/action/rest-template/**

            - id: action_interceptor_service_route
              uri: lb://ACTION-SERVICE-WITH-INTERCEPTOR
              predicates:
                  - Path=/action/interceptors/**

            - id: action_service_route
              uri: lb://ACTION-SERVICE
              predicates:
                - Path=/action/**
                - Method=POST, PUT, DELETE, GET

            - id: query_service_route
              uri: lb://QUERY-SERVICE
              predicates:
                - Path=/query/**
                - Method=GET
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/

security:
  secret-key: c2l0dGluZ2RyaW5rZWFydGhjZW50cmFsYml0eWFyZG1ha2ViYXNlcmVhbGl6ZWFib2E=

