server:
  port: 8083

spring:
  application:
    name: ACTION-SERVICE-REST

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/

resilience4j:
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      QUERY-SERVICE:
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

  retry:
    retryAspectOrder: 2
    instances:
      QUERY-SERVICE:
        maxAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.ResourceAccessException  # 1. Network/IO Failures
          - org.springframework.web.client.HttpServerErrorException # 2. HTTP 5xx Errors
          - java.io.IOException                                     # 3. Catch-all for underlying IO
          - java.lang.IllegalStateException                         # 4. Client-side LoadBalancer Failures

management:
  endpoints:
    web:
      exposure:
        include: "*"


