server:
  port: 8090

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: demouser
    password: ${password_demouser}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: admin
      password: admin

security:
  secret-key: bmF0dXJlb2J0YWlubG9vc2V0cmlwaGlnaGVzdHZpZXdyZW1hcmthYmxlYmVjb21ldG8=
  expiration-time:
    access-minutes: 30
    refresh-days: 7
  token-type:
    refresh-token: "refreshToken"
    access-token: "accessToken"